project:
  type: book

book:
  title: "A Guide to Indigenous Co-Management and Food Sovereignty in the Pacific Coast of North America"
  author: "Conner Smith"
  date: "5/14/2023"
  chapters:
    - index.qmd
    - native_lands.qmd
    - co_mgmt.qmd
    - food_sov.qmd
    - research.qmd

execute:
  echo: false
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



